### ISSUE TITLE
Contact people for  grants

### ISSUE THREAD

**Issue by vainmantas** [evanwsun/eleMENT-2016-2017#12]
Gain an understanding of what we need to do

**Comment by evanwsun** [comment]
https://www.mbfinancial.com/about-mb/giving-back-to-the-communities-we-serve/mb-financial-charitable-foundation/index.aspx

https://fconline.foundationcenter.org/grantmaker-profile/?collection=grantmakers&activity=result&key=HUGH044

http://www.entre-ed.org/_network/funders.pd

Here are some of the links I found
