### ISSUE TITLE
Content Structure

### ISSUE THREAD

**Issue by vainmantas** [evanwsun/eleMENT-2016-2017#16]
Are we going to be changing how we structure things for new content? Or should we stick with the same model?

**Comment by evanwsun** [comment]
What do you mean? In terms of the BML cycle? I mean, I'm down for trying new shit. We should always be trying to find new ways to make it better.

**Comment by vainmantas** [comment]
3 or different number of mods? Concurrent sessions? Not just BML per mod or more/less?  We could just save new content for the trial mods though and stick with BML.
